apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1 # Start with 1, let HPA handle scaling
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/PROJECT_ID/backend:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "50m" # Lowered for e2-micro compatibility
              memory: "64Mi" # Minimal memory for Node.js
            limits:
              cpu: "200m" # Reduced to allow multiple pods
              memory: "128Mi" # Conservative memory limit
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
